//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin_Login
{
    public string Email { get; set; }
    public string Password { get; set; }
}

public partial class Category_Info
{
    public int Cat_Id { get; set; }
    public string Cat_Name { get; set; }
    public string Cat_Img { get; set; }
}

public partial class oe_exams
{
    public int examid { get; set; }
    public Nullable<int> mid { get; set; }
    public Nullable<int> sid { get; set; }
    public Nullable<int> noq { get; set; }
    public Nullable<int> nocans { get; set; }
    public Nullable<System.DateTime> stdate { get; set; }
    public Nullable<System.DateTime> enddate { get; set; }

    public virtual Sub_Info Sub_Info { get; set; }
}

public partial class oe_members
{
    public int mid { get; set; }
    public string lname { get; set; }
    public string pwd { get; set; }
    public string fullname { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> dlv { get; set; }
    public Nullable<System.DateTime> dr { get; set; }
}

public partial class oe_questions
{
    public int qid { get; set; }
    public string question { get; set; }
    public string ans1 { get; set; }
    public string ans2 { get; set; }
    public string ans3 { get; set; }
    public string ans4 { get; set; }
    public string cans { get; set; }
    public Nullable<int> sid { get; set; }
}

public partial class oe_subjects
{
    public int sid { get; set; }
    public string sname { get; set; }
    public Nullable<int> noq { get; set; }
}

public partial class Ques_Info
{
    public int Q_Id { get; set; }
    public string Q_Name { get; set; }
    public string Option1 { get; set; }
    public string Option2 { get; set; }
    public string Option3 { get; set; }
    public string Option4 { get; set; }
    public Nullable<int> C_Ans { get; set; }
    public Nullable<int> Sub_Id { get; set; }

    public virtual Sub_Info Sub_Info { get; set; }
}

public partial class Student_Details
{
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Address { get; set; }
    public string Email_Id { get; set; }
    public string Phone_Number { get; set; }
    public int Student_Id { get; set; }
}

public partial class Student_LogIn
{
    public string Email { get; set; }
    public string Password { get; set; }
    public string Security_Question { get; set; }
    public string Answer { get; set; }
}

public partial class Sub_Info
{
    public Sub_Info()
    {
        this.oe_exams = new HashSet<oe_exams>();
        this.Ques_Info = new HashSet<Ques_Info>();
    }

    public int Sub_Id { get; set; }
    public string Sub_Name { get; set; }
    public Nullable<int> Correct_Marks { get; set; }
    public Nullable<int> Negative_Marks { get; set; }
    public string Percentage_Marks { get; set; }

    public virtual ICollection<oe_exams> oe_exams { get; set; }
    public virtual ICollection<Ques_Info> Ques_Info { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class User_Info
{
    public int uid { get; set; }
    public string name { get; set; }
    public string addrs { get; set; }
    public string city { get; set; }
    public string gender { get; set; }
    public string password { get; set; }
}

public partial class sp_GetQuestion_Result
{
    public string Q_Name { get; set; }
    public string Option1 { get; set; }
    public string Option2 { get; set; }
    public string Option3 { get; set; }
    public string Option4 { get; set; }
    public Nullable<int> C_Ans { get; set; }
}

public partial class sp_GetSubject_Result
{
    public int Sub_Id { get; set; }
    public string Sub_Name { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
